#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Classify each paper into L3 topics using an OpenAI-compatible Chat Completions API.

Input files expected:
  1) L3 topic file: JSONL, each line like:
     {
       "topic_L2": "Probabilistic methods",
       "topics_L3": [
         {"id": "T01", "name_en": "...", "description_en": "..."}, ...
       ]
     }

  2) Paper file: JSONL, each line like:
     {
       "paper_id": "00001",
       "title": "...",
       "abstract": "...",
       "canonical_topic": "Probabilistic methods"
     }

Important design:
  - The LLM does NOT receive canonical_topic / L2 topic.
  - canonical_topic is used only inside this script to choose the candidate L3 list.
  - Papers are grouped by canonical_topic/L2 before batching.
  - Each LLM call contains papers from exactly one L2 topic.
  - Shared candidate L3 topics with id/name_en/description_en are placed once in the system prompt.
  - The user prompt contains only paper_id/title/abstract for the current batch.
  - The LLM returns ONLY L3 id + English name, no reason.
  - This script strictly validates id/name_en pairs against the candidate list.
  - If id/name_en do not exactly match, the batch is regenerated by the LLM.
  - After 3 validation attempts by default, successful rows are written to --output.
  - Failed rows are written to --failed-output, not --output.
  - Resume is supported: existing paper_id values in --output are skipped.
  - Because --output contains only successful rows, failed papers are retried on rerun.
  - Optional concurrency is supported with --concurrency. Use --concurrency 3 to run 3 LLM requests at once.

Example:
  python classify_l3_topics_llm_v10.py \
    --base-url https://api.deepseek.com/v1 \
    --api-key "$DEEPSEEK_API_KEY" \
    --model deepseek-chat \
    --topics ml_l3_topics_all.jsonl \
    --input iclr2026_rejected_topics_map.jsonl \
    --output iclr2026_rejected_l3_topics.jsonl \
    --concurrency 3

For OpenRouter / MiniMax / local OpenAI-compatible endpoints, just change --base-url and --model.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import os
import re
import sys
import time
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

try:
    from openai import OpenAI
except ImportError:  # pragma: no cover
    OpenAI = None  # type: ignore


# -----------------------------
# JSONL helpers
# -----------------------------

def read_jsonl(path: str) -> Iterable[Dict[str, Any]]:
    with open(path, "r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as e:
                raise ValueError(f"Invalid JSON at {path}:{line_no}: {e}") from e
            if not isinstance(obj, dict):
                raise ValueError(f"Expected JSON object at {path}:{line_no}, got {type(obj).__name__}")
            yield obj


def append_jsonl(path: str, rows: Sequence[Dict[str, Any]]) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
        f.flush()
        os.fsync(f.fileno())


def load_done_ids(output_path: str, failed_output_path: str) -> Tuple[set[str], Dict[str, Any]]:
    """Load completed paper_ids from the success-only output JSONL.

    --output should contain successful rows only. If an older output file contains
    rows marked validation_failed_after_retries=true, this function migrates those
    rows into --failed-output and rewrites --output without them. Those paper_ids are
    NOT treated as done, so they will be retried on rerun.
    """
    done: set[str] = set()
    stats: Dict[str, Any] = {
        "existing_rows": 0,
        "done_rows": 0,
        "migrated_failed_rows": 0,
        "invalid_rows": 0,
        "failed_output_path": failed_output_path,
    }
    if not output_path or not os.path.exists(output_path):
        return done, stats

    success_or_kept_lines: List[str] = []
    failed_rows_to_migrate: List[Dict[str, Any]] = []

    with open(output_path, "r", encoding="utf-8") as f:
        for line_no, raw_line in enumerate(f, start=1):
            line = raw_line.strip()
            if not line:
                continue
            stats["existing_rows"] += 1
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                stats["invalid_rows"] += 1
                print(f"[warn] keep invalid output line {line_no} when loading done ids", file=sys.stderr)
                success_or_kept_lines.append(raw_line if raw_line.endswith("\n") else raw_line + "\n")
                continue

            if obj.get("validation_failed_after_retries") is True:
                stats["migrated_failed_rows"] += 1
                obj.setdefault("failure_source", "migrated_from_old_output")
                failed_rows_to_migrate.append(obj)
                continue

            pid = obj.get("paper_id")
            if pid is not None:
                done.add(str(pid))
                stats["done_rows"] += 1
            success_or_kept_lines.append(raw_line if raw_line.endswith("\n") else raw_line + "\n")

    if failed_rows_to_migrate:
        append_jsonl(failed_output_path, failed_rows_to_migrate)
        with open(output_path, "w", encoding="utf-8") as of:
            of.writelines(success_or_kept_lines)

    return done, stats


# -----------------------------
# Data normalization
# -----------------------------

def norm_text(s: Any) -> str:
    return " ".join(str(s or "").strip().split())


def norm_key(s: Any) -> str:
    return norm_text(s).lower()


def short_abstract(text: str, max_chars: int) -> str:
    text = norm_text(text)
    if max_chars <= 0 or len(text) <= max_chars:
        return text
    return text[:max_chars].rstrip() + "..."


@dataclass
class L3Topic:
    id: str
    name_en: str
    description_en: str

    def to_prompt_dict(self) -> Dict[str, str]:
        return {
            "id": self.id,
            "name_en": self.name_en,
            "description_en": self.description_en,
        }

    def to_output_dict(self, include_description: bool = False) -> Dict[str, str]:
        out = {"id": self.id, "name_en": self.name_en}
        if include_description:
            out["description_en"] = self.description_en
        return out


def load_l3_topics(topic_path: str) -> Tuple[Dict[str, List[L3Topic]], Dict[str, str]]:
    """Return exact L2 -> L3 list, and normalized L2 -> exact L2."""
    l2_to_l3: Dict[str, List[L3Topic]] = {}
    norm_to_exact: Dict[str, str] = {}

    for obj in read_jsonl(topic_path):
        l2 = norm_text(obj.get("topic_L2"))
        if not l2:
            continue
        raw_topics = obj.get("topics_L3") or []
        if not isinstance(raw_topics, list):
            raise ValueError(f"topics_L3 for L2={l2!r} must be a list")

        topics: List[L3Topic] = []
        for t in raw_topics:
            if not isinstance(t, dict):
                continue
            tid = norm_text(t.get("id"))
            name_en = norm_text(t.get("name_en"))
            # The user explicitly wants description_en in the LLM input.
            # Fall back to description only if description_en is missing.
            desc_en = norm_text(t.get("description_en") or t.get("description"))
            if not tid or not name_en:
                continue
            topics.append(L3Topic(id=tid, name_en=name_en, description_en=desc_en))

        l2_to_l3[l2] = topics
        norm_to_exact[norm_key(l2)] = l2

    return l2_to_l3, norm_to_exact


def find_l3_candidates(
    paper: Dict[str, Any],
    l2_to_l3: Dict[str, List[L3Topic]],
    norm_to_exact_l2: Dict[str, str],
) -> Tuple[List[L3Topic], Optional[str], Optional[str]]:
    """Find candidate L3 topics by paper['canonical_topic'].

    Returns: (candidates, matched_l2, warning)
    matched_l2 is only for internal/debug output if requested. It is not sent to LLM.
    """
    canonical = norm_text(paper.get("canonical_topic"))
    if not canonical:
        return [], None, "missing canonical_topic"

    if canonical in l2_to_l3:
        return l2_to_l3[canonical], canonical, None

    exact = norm_to_exact_l2.get(norm_key(canonical))
    if exact and exact in l2_to_l3:
        return l2_to_l3[exact], exact, f"canonical_topic normalized from {canonical!r} to {exact!r}"

    return [], None, f"no L3 topic candidates found for canonical_topic={canonical!r}"


# -----------------------------
# Prompt + LLM call
# -----------------------------

def build_prompt_papers(
    papers: Sequence[Dict[str, Any]],
    max_abstract_chars: int,
) -> List[Dict[str, Any]]:
    """Build the user prompt payload.

    Candidate L3 topics are intentionally NOT repeated per paper. In this version,
    each LLM call contains papers from exactly one L2 topic, so the shared candidate
    L3 list is placed once in the system prompt.
    """
    prompt_papers: List[Dict[str, Any]] = []
    for p in papers:
        pid = str(p.get("paper_id", ""))
        prompt_papers.append(
            {
                "paper_id": pid,
                "title": norm_text(p.get("title")),
                "abstract": short_abstract(str(p.get("abstract") or ""), max_abstract_chars),
            }
        )
    return prompt_papers


def build_messages(
    prompt_papers: Sequence[Dict[str, Any]],
    candidate_l3_topics: Sequence[L3Topic],
) -> List[Dict[str, str]]:
    """Build messages for one batch.

    All papers in this call must come from the same L2 topic. The candidate L3
    topics for that L2 are placed once in the system prompt. The user prompt only
    contains paper_id/title/abstract.
    """
    system_obj: Dict[str, Any] = {
        "role": "You are an expert machine learning paper topic classifier.",
        "task": (
            "Assign each paper to one or more L3 topics from the shared candidate_L3_topics list. "
            "All papers in this request belong to the same already-known L2 topic, but the L2 topic name is not needed. "
            "Use the paper title and abstract only. Do not invent topics."
        ),
        "candidate_L3_topics": [t.to_prompt_dict() for t in candidate_l3_topics],
        "classification_rules": [
            "For each paper, select the most relevant L3 topic(s) from the shared candidate_L3_topics list.",
            "A paper may have multiple L3 topics if multiple candidates are clearly central.",
            "Usually choose 1 to 3 topics.",
            "If none are suitable, return an empty selected_L3_topics list.",
            "For each selected topic, copy BOTH id and name_en exactly from candidate_L3_topics.",
            "Do not return reason, rationale, explanation, confidence, or any extra fields.",
        ],
        "output_schema": {
            "papers": [
                {
                    "paper_id": "string",
                    "selected_L3_topics": [
                        {
                            "id": "exact candidate topic id",
                            "name_en": "exact candidate English topic name",
                        }
                    ],
                }
            ]
        },
        "output_constraints": [
            "Return valid JSON only.",
            "Do not include markdown fences.",
            "Do not include text outside the JSON object.",
        ],
    }

    user_obj: Dict[str, Any] = {
        "papers": list(prompt_papers),
    }
    system = json.dumps(system_obj, ensure_ascii=False, indent=2)
    user = json.dumps(user_obj, ensure_ascii=False, indent=2)
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]



def extract_json_object(text: str) -> Dict[str, Any]:
    """Parse a JSON object from an LLM response.

    The prompt asks for JSON only, but some models still wrap output in markdown
    fences or add short leading/trailing text. This helper keeps the script usable
    across DeepSeek/MiniMax/OpenRouter/local OpenAI-compatible services.
    """
    raw = (text or "").strip()
    if not raw:
        raise ValueError("empty LLM response")

    # Remove common markdown fences.
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json|JSON)?\s*", "", raw).strip()
        raw = re.sub(r"\s*```$", "", raw).strip()

    try:
        obj = json.loads(raw)
    except json.JSONDecodeError:
        # Fallback: extract the first balanced top-level JSON object.
        start = raw.find("{")
        if start < 0:
            raise
        depth = 0
        in_str = False
        escape = False
        end = -1
        for i in range(start, len(raw)):
            ch = raw[i]
            if in_str:
                if escape:
                    escape = False
                elif ch == "\\":
                    escape = True
                elif ch == '"':
                    in_str = False
            else:
                if ch == '"':
                    in_str = True
                elif ch == "{":
                    depth += 1
                elif ch == "}":
                    depth -= 1
                    if depth == 0:
                        end = i + 1
                        break
        if end < 0:
            raise
        obj = json.loads(raw[start:end])

    if not isinstance(obj, dict):
        raise ValueError(f"LLM JSON root must be an object, got {type(obj).__name__}")
    return obj


def _create_chat_completion(
    client: Any,
    model: str,
    messages: List[Dict[str, str]],
    temperature: float,
    max_tokens: int,
    use_response_format: bool,
) -> Any:
    kwargs: Dict[str, Any] = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    if use_response_format:
        kwargs["response_format"] = {"type": "json_object"}
    return client.chat.completions.create(**kwargs)


def call_llm(
    client: Any,
    model: str,
    messages: List[Dict[str, str]],
    temperature: float,
    max_tokens: int,
    response_format_mode: str,
) -> Tuple[Dict[str, Any], str, bool]:
    """Call an OpenAI-compatible Chat Completions API and return parsed JSON.

    response_format_mode:
      - on:   always use response_format={"type":"json_object"}
      - off:  never use response_format
      - auto: try with response_format first, then retry once without it if the
              endpoint rejects that parameter or returns malformed output.
    """
    if client is None:
        raise ValueError("client is None; use --dry-run to avoid API calls")

    modes: List[bool]
    if response_format_mode == "on":
        modes = [True]
    elif response_format_mode == "off":
        modes = [False]
    else:
        modes = [True, False]

    last_error: Optional[Exception] = None
    last_raw = ""
    for use_rf in modes:
        try:
            resp = _create_chat_completion(
                client=client,
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                use_response_format=use_rf,
            )
            raw_text = resp.choices[0].message.content or ""
            last_raw = raw_text
            return extract_json_object(raw_text), raw_text, use_rf
        except Exception as e:  # noqa: BLE001
            last_error = e
            # In explicit on/off mode, do not silently change behavior.
            if response_format_mode in {"on", "off"}:
                break
            # In auto mode, retry once without response_format.
            continue

    if last_raw:
        raise ValueError(f"failed to parse LLM JSON. Last raw response starts with: {last_raw[:500]!r}") from last_error
    raise RuntimeError(f"LLM call failed: {last_error}") from last_error


# -----------------------------
# Validation
# -----------------------------

def normalize_selected_topics(value: Any) -> List[Dict[str, str]]:
    """Accept the intended schema, plus a few common malformed variants."""
    if value is None:
        return []
    if isinstance(value, dict):
        value = [value]
    if not isinstance(value, list):
        return []

    out: List[Dict[str, str]] = []
    for item in value:
        if isinstance(item, dict):
            tid = norm_text(item.get("id") or item.get("topic_id") or item.get("L3topic_id"))
            name = norm_text(item.get("name_en") or item.get("topic_name_en") or item.get("name") or item.get("L3topic"))
            out.append({"id": tid, "name_en": name})
        elif isinstance(item, str):
            s = norm_text(item)
            out.append({"id": s, "name_en": s})
    return out


def validate_one_paper(
    paper: Dict[str, Any],
    model_item: Optional[Dict[str, Any]],
    candidates: List[L3Topic],
    include_description_in_output: bool,
    include_validation_warnings: bool,
    include_canonical_topic: bool,
    matched_l2: Optional[str],
    pre_warning: Optional[str] = None,
) -> Tuple[Dict[str, Any], List[str], bool]:
    """Validate LLM topic id/name_en pairs strictly.

    Important behavior:
      - If id is correct but name_en is missing/wrong, mark hard_error=True.
      - If name_en is correct but id is missing/wrong, mark hard_error=True.
      - The returned row still uses the canonical candidate table to produce a clean final output,
        but the hard error forces the caller to ask the LLM to regenerate until attempts are exhausted.

    Returns: (output_row, warnings, has_hard_error)
    has_hard_error means we should retry if possible.
    """
    pid = str(paper.get("paper_id", ""))
    warnings: List[str] = []
    hard_error = False
    if pre_warning:
        warnings.append(pre_warning)

    id_map = {t.id: t for t in candidates}
    # exact English name -> topic
    name_map = {t.name_en: t for t in candidates}
    # lower/normalized English name -> topic, only if unique
    norm_name_to_topics: Dict[str, List[L3Topic]] = {}
    for t in candidates:
        norm_name_to_topics.setdefault(norm_key(t.name_en), []).append(t)

    if model_item is None:
        selected_raw: Any = []
        warnings.append("LLM output missing this paper_id; selected_L3_topics set to empty")
        hard_error = True
    else:
        selected_raw = (
            model_item.get("selected_L3_topics")
            if "selected_L3_topics" in model_item
            else model_item.get("L3topic_ids")
            if "L3topic_ids" in model_item
            else model_item.get("L3topic")
        )

    selected = normalize_selected_topics(selected_raw)
    fixed_topics: List[L3Topic] = []
    seen_ids: set[str] = set()

    for st in selected:
        raw_id = norm_text(st.get("id"))
        raw_name = norm_text(st.get("name_en"))
        topic: Optional[L3Topic] = None

        if raw_id in id_map:
            topic = id_map[raw_id]
            if raw_name != topic.name_en:
                warnings.append(
                    f"topic id/name_en mismatch: id={raw_id!r} is valid, "
                    f"but LLM name_en={raw_name!r}; expected name_en={topic.name_en!r}"
                )
                hard_error = True
        elif raw_name in name_map:
            topic = name_map[raw_name]
            warnings.append(
                f"topic name_en/id mismatch: name_en={raw_name!r} is valid, "
                f"but LLM id={raw_id!r}; expected id={topic.id!r}"
            )
            hard_error = True
        else:
            norm_name = norm_key(raw_name)
            maybe = norm_name_to_topics.get(norm_name, [])
            if len(maybe) == 1:
                topic = maybe[0]
                warnings.append(
                    f"topic name_en/id mismatch after normalization: name_en={raw_name!r} maps to "
                    f"expected id={topic.id!r}, expected name_en={topic.name_en!r}; LLM id={raw_id!r}"
                )
                hard_error = True

        if topic is None:
            warnings.append(f"invalid selected L3 topic dropped: id={raw_id!r}, name_en={raw_name!r}")
            hard_error = True
            continue

        if topic.id not in seen_ids:
            fixed_topics.append(topic)
            seen_ids.add(topic.id)

    row: Dict[str, Any] = {
        "paper_id": pid,
        "title": norm_text(paper.get("title")),
        "L3topic_ids": [t.id for t in fixed_topics],
        "L3topic": [t.name_en for t in fixed_topics],
        "L3topic_detail": [t.to_output_dict(include_description=include_description_in_output) for t in fixed_topics],
    }
    if include_canonical_topic:
        # This is copied from the original file only; it is not produced by the LLM.
        row["canonical_topic"] = norm_text(paper.get("canonical_topic"))
        if matched_l2:
            row["matched_L2_for_candidate_lookup"] = matched_l2
    if include_validation_warnings and warnings:
        row["validation_warnings"] = warnings

    return row, warnings, hard_error


def validate_batch(
    batch: Sequence[Dict[str, Any]],
    llm_obj: Dict[str, Any],
    paper_candidates: Dict[str, List[L3Topic]],
    include_description_in_output: bool,
    include_validation_warnings: bool,
    include_canonical_topic: bool,
    matched_l2_map: Dict[str, Optional[str]],
    pre_warnings: Dict[str, Optional[str]],
) -> Tuple[List[Dict[str, Any]], List[str], bool]:
    papers_out = llm_obj.get("papers")
    if not isinstance(papers_out, list):
        papers_out = []

    model_by_pid: Dict[str, Dict[str, Any]] = {}
    duplicate_pids: set[str] = set()
    for item in papers_out:
        if not isinstance(item, dict):
            continue
        pid = str(item.get("paper_id", ""))
        if not pid:
            continue
        if pid in model_by_pid:
            duplicate_pids.add(pid)
        model_by_pid[pid] = item

    batch_warnings: List[str] = []
    has_hard_error = False
    rows: List[Dict[str, Any]] = []

    if duplicate_pids:
        batch_warnings.append(f"LLM returned duplicate paper_id values: {sorted(duplicate_pids)}")
        has_hard_error = True

    for p in batch:
        pid = str(p.get("paper_id", ""))
        row, warnings, hard_error = validate_one_paper(
            paper=p,
            model_item=model_by_pid.get(pid),
            candidates=paper_candidates[pid],
            include_description_in_output=include_description_in_output,
            include_validation_warnings=include_validation_warnings,
            include_canonical_topic=include_canonical_topic,
            matched_l2=matched_l2_map.get(pid),
            pre_warning=pre_warnings.get(pid),
        )
        # Internal flag used only by the main loop to split success vs failed rows.
        # It is removed before writing JSONL files.
        row["_validation_hard_error"] = hard_error
        rows.append(row)
        for w in warnings:
            batch_warnings.append(f"paper_id={pid}: {w}")
        has_hard_error = has_hard_error or hard_error

    extra_pids = sorted(set(model_by_pid) - {str(p.get("paper_id", "")) for p in batch})
    if extra_pids:
        batch_warnings.append(f"LLM returned unexpected paper_id values not in batch: {extra_pids}")
        has_hard_error = True

    return rows, batch_warnings, has_hard_error


# -----------------------------
# Main loop
# -----------------------------

def batched(items: Sequence[Dict[str, Any]], n: int) -> Iterable[List[Dict[str, Any]]]:
    for i in range(0, len(items), n):
        yield list(items[i : i + n])


@dataclass
class BatchTask:
    call_index: int
    l2_index: int
    total_l2_groups: int
    l2_key: str
    local_batch_index: int
    batch_for_llm: List[Dict[str, Any]]
    shared_candidates: List[L3Topic]


@dataclass
class BatchResult:
    call_index: int
    l2_index: int
    total_l2_groups: int
    local_batch_index: int
    success_rows: List[Dict[str, Any]]
    failed_rows: List[Dict[str, Any]]
    warnings: List[str]
    info: str
    response_format_used: bool


def split_validated_rows(
    final_rows: List[Dict[str, Any]],
    final_warnings: List[str],
    final_has_hard_error: bool,
    include_validation_warnings: bool,
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Split validated rows into success rows and failed rows.

    This helper is used by both serial and concurrent execution. It keeps
    --output success-only and sends failed rows to --failed-output.
    """
    warning_text_by_pid: Dict[str, List[str]] = {}
    for w in final_warnings:
        m = re.match(r"paper_id=([^:]+):\s*(.*)", w)
        if m:
            warning_text_by_pid.setdefault(m.group(1), []).append(m.group(2))

    success_rows: List[Dict[str, Any]] = []
    failed_rows: List[Dict[str, Any]] = []
    batch_level_failure = final_has_hard_error and any(
        (not w.startswith("paper_id=")) for w in final_warnings
    )

    for row in final_rows:
        row_failed = bool(row.pop("_validation_hard_error", False)) or batch_level_failure
        if row_failed:
            row["validation_failed_after_retries"] = True
            row["failure_type"] = "validation_failed_after_retries"
            if "validation_warnings" not in row:
                row["validation_warnings"] = warning_text_by_pid.get(str(row.get("paper_id", "")), [])
            if batch_level_failure:
                row.setdefault(
                    "batch_validation_warnings",
                    [w for w in final_warnings if not w.startswith("paper_id=")],
                )
            failed_rows.append(row)
        else:
            row.pop("validation_failed_after_retries", None)
            row.pop("validation_warnings", None) if not include_validation_warnings else None
            success_rows.append(row)

    return success_rows, failed_rows


def make_api_failed_rows(
    task: BatchTask,
    paper_candidates: Dict[str, List[L3Topic]],
    matched_l2_map: Dict[str, Optional[str]],
    pre_warnings: Dict[str, Optional[str]],
    args: argparse.Namespace,
    error_message: str,
) -> List[Dict[str, Any]]:
    """Create failed-output rows when the API/JSON call fails completely."""
    failed_rows: List[Dict[str, Any]] = []
    for paper in task.batch_for_llm:
        pid = str(paper.get("paper_id", ""))
        row, warnings, _ = validate_one_paper(
            paper=paper,
            model_item=None,
            candidates=paper_candidates[pid],
            include_description_in_output=args.include_description_in_output,
            include_validation_warnings=True,
            include_canonical_topic=args.include_canonical_topic,
            matched_l2=matched_l2_map.get(pid),
            pre_warning=pre_warnings.get(pid),
        )
        row.pop("_validation_hard_error", None)
        row["validation_failed_after_retries"] = True
        row["failure_type"] = "api_or_json_failed_after_retries"
        row["validation_warnings"] = warnings + [error_message]
        failed_rows.append(row)
    return failed_rows


def process_llm_batch(
    task: BatchTask,
    args: argparse.Namespace,
    matched_l2_map: Dict[str, Optional[str]],
    pre_warnings: Dict[str, Optional[str]],
) -> BatchResult:
    """Run one LLM batch.

    This function is intentionally self-contained so it can run inside a
    ThreadPoolExecutor worker. Each worker creates its own OpenAI client instead
    of sharing one client across threads.
    """
    if OpenAI is None:
        raise RuntimeError("Missing dependency: pip install openai")

    client = OpenAI(api_key=args.api_key, base_url=args.base_url)
    paper_candidates: Dict[str, List[L3Topic]] = {
        str(p.get("paper_id", "")): task.shared_candidates for p in task.batch_for_llm
    }
    prompt_papers = build_prompt_papers(task.batch_for_llm, args.max_abstract_chars)

    final_rows: Optional[List[Dict[str, Any]]] = None
    final_warnings: List[str] = []
    final_has_hard_error = False
    used_rf = False
    worker_warnings: List[str] = []

    for validation_attempt in range(1, args.max_validation_attempts + 1):
        # Reuse the same prompt on validation retries. Do not feed previous error details back to the model.
        messages = build_messages(prompt_papers, task.shared_candidates)

        last_exc: Optional[Exception] = None
        llm_obj: Optional[Dict[str, Any]] = None
        used_rf = False

        for api_attempt in range(1, args.max_api_retries + 1):
            try:
                llm_obj, _raw_text, used_rf = call_llm(
                    client=client,
                    model=args.model,
                    messages=messages,
                    temperature=args.temperature,
                    max_tokens=args.max_tokens,
                    response_format_mode=args.response_format_mode,
                )
                break
            except Exception as e:  # noqa: BLE001
                last_exc = e
                worker_warnings.append(
                    f"API/JSON call failed call={task.call_index} l2_group={task.l2_index} "
                    f"batch={task.local_batch_index} api_attempt={api_attempt}/{args.max_api_retries}: {e}"
                )
                if api_attempt < args.max_api_retries:
                    wait = min(2 ** (api_attempt - 1), 20)
                    time.sleep(wait)

        if llm_obj is None:
            err = f"LLM call failed after retries: {last_exc}"
            failed_rows = make_api_failed_rows(
                task=task,
                paper_candidates=paper_candidates,
                matched_l2_map=matched_l2_map,
                pre_warnings=pre_warnings,
                args=args,
                error_message=err,
            )
            if args.sleep > 0:
                time.sleep(args.sleep)
            return BatchResult(
                call_index=task.call_index,
                l2_index=task.l2_index,
                total_l2_groups=task.total_l2_groups,
                local_batch_index=task.local_batch_index,
                success_rows=[],
                failed_rows=failed_rows,
                warnings=worker_warnings + [err],
                info=(
                    f"call={task.call_index} l2_group={task.l2_index}/{task.total_l2_groups} "
                    f"batch={task.local_batch_index} wrote success=0 to output, "
                    f"failed={len(failed_rows)} to failed_output; response_format_used={used_rf}"
                ),
                response_format_used=used_rf,
            )

        # On the final failed attempt, always store warnings in failed rows so the failure is recorded.
        store_warnings_this_attempt = args.include_validation_warnings or validation_attempt == args.max_validation_attempts

        rows, warnings, has_hard_error = validate_batch(
            batch=task.batch_for_llm,
            llm_obj=llm_obj,
            paper_candidates=paper_candidates,
            include_description_in_output=args.include_description_in_output,
            include_validation_warnings=store_warnings_this_attempt,
            include_canonical_topic=args.include_canonical_topic,
            matched_l2_map=matched_l2_map,
            pre_warnings=pre_warnings,
        )
        final_rows = rows
        final_warnings = warnings
        final_has_hard_error = has_hard_error

        if not has_hard_error:
            break

        if validation_attempt < args.max_validation_attempts:
            worker_warnings.append(
                f"validation failed call={task.call_index}; retrying "
                f"validation_attempt={validation_attempt + 1}/{args.max_validation_attempts}"
            )

    if final_rows is None:
        raise RuntimeError("internal error: final_rows is None")

    success_rows, failed_rows = split_validated_rows(
        final_rows=final_rows,
        final_warnings=final_warnings,
        final_has_hard_error=final_has_hard_error,
        include_validation_warnings=args.include_validation_warnings,
    )

    if args.sleep > 0:
        time.sleep(args.sleep)

    return BatchResult(
        call_index=task.call_index,
        l2_index=task.l2_index,
        total_l2_groups=task.total_l2_groups,
        local_batch_index=task.local_batch_index,
        success_rows=success_rows,
        failed_rows=failed_rows,
        warnings=worker_warnings + final_warnings,
        info=(
            f"call={task.call_index} l2_group={task.l2_index}/{task.total_l2_groups} "
            f"batch={task.local_batch_index} wrote success={len(success_rows)} to output, "
            f"failed={len(failed_rows)} to failed_output; response_format_used={used_rf}"
        ),
        response_format_used=used_rf,
    )


def write_batch_result(result: BatchResult, output_path: str, failed_output_path: str) -> None:
    """Write one completed batch result from the main thread only."""
    if result.success_rows:
        append_jsonl(output_path, result.success_rows)
    if result.failed_rows:
        append_jsonl(failed_output_path, result.failed_rows)

    for w in result.warnings:
        print(f"[warn] {w}", file=sys.stderr)
    print(f"[info] {result.info}", file=sys.stderr)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Classify papers into L3 topics using an OpenAI-compatible API."
    )
    parser.add_argument("--topics", required=True, help="Path to ml_l3_topics_all.jsonl")
    parser.add_argument("--input", required=True, help="Path to paper JSONL, e.g. iclr2026_rejected_topics_map.jsonl")
    parser.add_argument("--output", required=True, help="Success-only output JSONL path")
    parser.add_argument(
        "--failed-output",
        default=None,
        help="Failed-record JSONL path. Default: <output>.failed.jsonl. Failed records are never written to --output.",
    )

    # No provider argument by design. User supplies base URL directly.
    parser.add_argument(
        "--base-url",
        default=os.getenv("LLM_BASE_URL") or os.getenv("OPENAI_BASE_URL") or "https://api.openai.com/v1",
        help="OpenAI-compatible base URL, e.g. https://api.deepseek.com/v1, https://api.minimax.io/v1, https://openrouter.ai/api/v1",
    )
    parser.add_argument(
        "--api-key",
        default=os.getenv("LLM_API_KEY") or os.getenv("OPENAI_API_KEY") or "EMPTY",
        help="API key. Can also use LLM_API_KEY or OPENAI_API_KEY. For local endpoints, EMPTY is okay if accepted.",
    )
    parser.add_argument(
        "--model",
        default=os.getenv("LLM_MODEL") or os.getenv("OPENAI_MODEL"),
        help="Model name, e.g. deepseek-chat, MiniMax-M1, gpt-4.1-mini, openai/gpt-4.1-mini. Can also use LLM_MODEL.",
    )

    parser.add_argument("--batch-size", type=int, default=5, help="Number of papers per LLM call. Default: 5")
    parser.add_argument("--limit", type=int, default=0, help="Classify only first N remaining papers. 0 means all.")
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument("--max-tokens", type=int, default=4096)
    parser.add_argument("--max-abstract-chars", type=int, default=4000)
    parser.add_argument("--sleep", type=float, default=0.0, help="Sleep seconds after each API call")
    parser.add_argument(
        "--concurrency",
        type=int,
        default=3,
        help="Number of concurrent LLM batch requests. Default: 1. Use 3 to send three requests at once.",
    )

    parser.add_argument(
        "--response-format-mode",
        choices=["auto", "on", "off"],
        default="auto",
        help="Use response_format={type:json_object}. auto retries without it if unsupported. Default: auto",
    )
    parser.add_argument("--max-api-retries", type=int, default=3)
    parser.add_argument(
        "--max-validation-attempts",
        type=int,
        default=3,
        help=(
            "Total validation attempts for a batch. If id/name_en pairs are not exact, "
            "the script asks the LLM to regenerate. After this many failed attempts, "
            "it records validation_failed_after_retries=true and writes warnings. Default: 3"
        ),
    )

    parser.add_argument("--dry-run", action="store_true", help="Print one prompt batch and exit without calling LLM")
    parser.add_argument("--print-config", action="store_true", help="Print resolved config and continue")
    parser.add_argument("--force", action="store_true", help="Do not skip paper_ids already in output")
    parser.add_argument(
        "--include-description-in-output",
        action="store_true",
        help="Also include description_en in L3topic_detail output. By default output detail only has id/name_en.",
    )
    parser.add_argument(
        "--include-validation-warnings",
        action="store_true",
        help=(
            "Write validation_warnings into output rows whenever there are warnings. "
            "Even if this flag is not set, warnings are still written for batches that fail all validation attempts."
        ),
    )
    parser.add_argument(
        "--include-canonical-topic",
        action="store_true",
        help="Copy canonical_topic from input into output for debugging. It is never produced by the LLM.",
    )

    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if not args.failed_output:
        args.failed_output = args.output + ".failed.jsonl"

    if args.batch_size <= 0:
        raise SystemExit("--batch-size must be positive")
    if args.concurrency <= 0:
        raise SystemExit("--concurrency must be positive")
    if args.max_validation_attempts <= 0:
        raise SystemExit("--max-validation-attempts must be positive")
    if not args.model:
        raise SystemExit("Missing --model. Provide --model or set LLM_MODEL / OPENAI_MODEL.")
    if OpenAI is None and not args.dry_run:
        raise SystemExit("Missing dependency: pip install openai")

    if args.print_config:
        redacted_key = "EMPTY" if args.api_key == "EMPTY" else (args.api_key[:4] + "..." + args.api_key[-4:])
        print(
            json.dumps(
                {
                    "base_url": args.base_url,
                    "api_key": redacted_key,
                    "model": args.model,
                    "batch_size": args.batch_size,
                    "concurrency": args.concurrency,
                    "batching_strategy": "group_by_L2_then_batch",
                    "response_format_mode": args.response_format_mode,
                    "success_output": args.output,
                    "failed_output": args.failed_output,
                },
                ensure_ascii=False,
                indent=2,
            )
        )

    l2_to_l3, norm_to_exact_l2 = load_l3_topics(args.topics)
    if not l2_to_l3:
        raise SystemExit(f"No L3 topics loaded from {args.topics}")

    all_papers = list(read_jsonl(args.input))
    if not all_papers:
        raise SystemExit(f"No papers loaded from {args.input}")

    if args.force:
        done_ids: set[str] = set()
        resume_stats: Dict[str, Any] = {
            "existing_rows": 0,
            "done_rows": 0,
            "migrated_failed_rows": 0,
            "invalid_rows": 0,
            "failed_output_path": args.failed_output,
        }
    else:
        done_ids, resume_stats = load_done_ids(args.output, args.failed_output)

    remaining: List[Dict[str, Any]] = []
    for p in all_papers:
        pid = str(p.get("paper_id", ""))
        if not pid:
            print("[warn] skip paper without paper_id", file=sys.stderr)
            continue
        if pid in done_ids:
            continue
        remaining.append(p)

    if args.limit and args.limit > 0:
        remaining = remaining[: args.limit]

    if resume_stats.get("migrated_failed_rows"):
        print(
            f"[info] migrated {resume_stats['migrated_failed_rows']} old failed rows from output "
            f"to failed_output={args.failed_output}; those papers will be retried",
            file=sys.stderr,
        )

    print(
        f"[info] loaded {len(all_papers)} papers; already done successful {len(done_ids)}; to process {len(remaining)}",
        file=sys.stderr,
    )

    if not remaining:
        print("[info] nothing to do", file=sys.stderr)
        return 0

    # ------------------------------------------------------------------
    # Group papers by matched L2 topic before batching.
    #
    # This is the key optimization requested by the user:
    #   - each LLM call contains only papers from the same L2 topic;
    #   - the candidate L3 list for that L2 is sent once in the system prompt;
    #   - the user prompt contains only the papers in that batch.
    #
    # We preserve first-seen L2 order from the input file. If a group size is
    # not divisible by --batch-size, its final smaller batch is still sent as-is.
    # ------------------------------------------------------------------
    grouped_papers: Dict[str, List[Dict[str, Any]]] = {}
    group_order: List[str] = []
    l2_candidates: Dict[str, List[L3Topic]] = {}
    matched_l2_map: Dict[str, Optional[str]] = {}
    pre_warnings: Dict[str, Optional[str]] = {}
    skipped_missing_candidates = 0
    direct_failed_rows: List[Dict[str, Any]] = []

    for p in remaining:
        pid = str(p.get("paper_id", ""))
        candidates, matched_l2, warn = find_l3_candidates(p, l2_to_l3, norm_to_exact_l2)
        matched_l2_map[pid] = matched_l2
        pre_warnings[pid] = warn

        if not candidates or not matched_l2:
            skipped_missing_candidates += 1
            row, _, _ = validate_one_paper(
                paper=p,
                model_item={"paper_id": pid, "selected_L3_topics": []},
                candidates=[],
                include_description_in_output=args.include_description_in_output,
                include_validation_warnings=args.include_validation_warnings,
                include_canonical_topic=args.include_canonical_topic,
                matched_l2=matched_l2,
                pre_warning=warn,
            )
            row["validation_failed_after_retries"] = True
            row["failure_type"] = "no_candidate_l3_topics"
            if "validation_warnings" not in row:
                row["validation_warnings"] = [warn or "no candidate L3 topics found"]
            direct_failed_rows.append(row)
            continue

        if matched_l2 not in grouped_papers:
            grouped_papers[matched_l2] = []
            group_order.append(matched_l2)
            l2_candidates[matched_l2] = candidates
        grouped_papers[matched_l2].append(p)

    if direct_failed_rows:
        append_jsonl(args.failed_output, direct_failed_rows)
        for r in direct_failed_rows:
            print(
                f"[warn] wrote failed record for paper_id={r['paper_id']} to failed_output because no candidate L3 topics were found",
                file=sys.stderr,
            )

    total_llm_papers = sum(len(grouped_papers[g]) for g in group_order)
    print(
        f"[info] grouped remaining papers into {len(group_order)} L2 groups; "
        f"LLM papers={total_llm_papers}; direct_failed_no_candidates={len(direct_failed_rows)}",
        file=sys.stderr,
    )

    tasks: List[BatchTask] = []
    call_index = 0

    for l2_index, l2_key in enumerate(group_order, start=1):
        group = grouped_papers[l2_key]
        shared_candidates = l2_candidates[l2_key]
        print(
            f"[info] L2 group {l2_index}/{len(group_order)}: papers={len(group)}, "
            f"candidate_L3={len(shared_candidates)}",
            file=sys.stderr,
        )

        for local_batch_index, batch_for_llm in enumerate(batched(group, args.batch_size), start=1):
            call_index += 1
            tasks.append(
                BatchTask(
                    call_index=call_index,
                    l2_index=l2_index,
                    total_l2_groups=len(group_order),
                    l2_key=l2_key,
                    local_batch_index=local_batch_index,
                    batch_for_llm=batch_for_llm,
                    shared_candidates=shared_candidates,
                )
            )

    if not tasks:
        print("[info] no LLM batches to process", file=sys.stderr)
    elif args.dry_run:
        first_task = tasks[0]
        prompt_papers = build_prompt_papers(first_task.batch_for_llm, args.max_abstract_chars)
        messages = build_messages(prompt_papers, first_task.shared_candidates)
        print(json.dumps({"messages": messages}, ensure_ascii=False, indent=2))
        print("\n[dry-run] no API call made; no output written for LLM batch", file=sys.stderr)
        return 0
    else:
        max_workers = min(args.concurrency, len(tasks))
        print(
            f"[info] prepared {len(tasks)} LLM batches; concurrency={max_workers}",
            file=sys.stderr,
        )

        # Write in call_index order for deterministic output, while still running API calls concurrently.
        completed_by_index: Dict[int, BatchResult] = {}
        next_to_write = 1

        if max_workers == 1:
            for task in tasks:
                result = process_llm_batch(
                    task=task,
                    args=args,
                    matched_l2_map=matched_l2_map,
                    pre_warnings=pre_warnings,
                )
                write_batch_result(result, args.output, args.failed_output)
        else:
            with ThreadPoolExecutor(max_workers=max_workers) as executor:
                future_to_call_index = {
                    executor.submit(
                        process_llm_batch,
                        task,
                        args,
                        matched_l2_map,
                        pre_warnings,
                    ): task.call_index
                    for task in tasks
                }

                for future in as_completed(future_to_call_index):
                    result = future.result()
                    completed_by_index[result.call_index] = result

                    while next_to_write in completed_by_index:
                        ordered_result = completed_by_index.pop(next_to_write)
                        write_batch_result(ordered_result, args.output, args.failed_output)
                        next_to_write += 1

    if skipped_missing_candidates:
        print(f"[warn] {skipped_missing_candidates} papers had no candidate L3 topics", file=sys.stderr)

    print(f"[info] done. success_output={args.output}; failed_output={args.failed_output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
